### PR TITLE
Change the license to MIT, no one likes GPL-3.0...

### PR DESCRIPTION
**Pull request by pagoru**

### CODE REVIEW

**Comment by cout970** [comment]
La Europea!

**Comment by Zambumon** [comment]
@pagoru @cout970 I'm in for the European Union Public License 1.1

**Comment by pagoru** [comment]
Change the license to MIT, no one uses EUPL 1.1...

**Comment by cout970** [comment]
https://github.com/Zambumon/TiendaVirutalDAWA
what's the problem with EU? don't you like the union?

**Comment by petrusboniatus** [comment]
Every body knows that MIT is neoliberlarist propaganda

**Pull request closed without merging**
